[BACKLOG-15575] - Fix DET tooltip to comply with UX specification.
webdetails/ccc-ext pull request #8
Opened 2017-03-31 18:07 UTC by marcoslarsen

@nantunes Please review.

2017-03-31 18:08 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-04-01 08:26 UTC, nantunes requested changes
Being the UX recommendation to use absolute px instead of relative em? Good luck when the base font size changes from 10px to 12px, or whatever... https://www.google.com/search?q=why+use+em+instead+of+px&oq=why+use+em+

2017-04-03 13:27 UTC, marcoslarsen commented
After talking with ux, they decided to keep em instead of px

2017-04-03 13:27 UTC, closed without merging

2017-04-03 13:28 UTC, nantunes commented
Will a new PR fix the paddings?